name:                anarchy
version:             0.1.0.0
github:              "Tevo45/anarchy"
license:             MIT
author:              "Estevan Castilho (Tevo45)"
maintainer:          "estevan.cps@gmail.com"
copyright:           "2021 Estevan Castilho"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/anarchy#readme>

dependencies:
- base >= 4.7 && < 5
- process
- regex-pcre-builtin
- split
- filepath
- req
- utf8-string
- text
- bytestring
- connection
- http-client
- http-client-tls
- transformers
- websockets
- wuss
- base64
- aeson
- containers
- mmorph

library:
  source-dirs: core

executables:
  anarchy-cli:
    main:                Main.hs
    source-dirs:         app-cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    # - -XSafe
    dependencies:
    - anarchy
